In [19]:
import numpy as np
import pandas as pd

### Dataframe as a generalized NumPy array

In [20]:
pop_dict = {'California':12345,
            'New York':12346,
            'Texas':147895,
            'Florida':968574}

area_dict = {'California': 423967,
            'New York': 141297,
            'Texas': 695662,
            'Florida': 170312}

population_series = pd.Series(pop_dict)
area_series = pd.Series(area_dict)

In [21]:
print(population_series)
print("\n")
print(area_series)

California     12345
New York       12346
Texas         147895
Florida       968574
dtype: int64


California    423967
New York      141297
Texas         695662
Florida       170312
dtype: int64

In [22]:
# Constructing a Dataframe from the above information
states = pd.DataFrame({"population": population_series,
                       "area": area_series})
states

            population    area
California       12345  423967
New York         12346  141297
Texas           147895  695662
Florida         968574  170312

#### Index

In [23]:
# Index - It gives access to the index labels
states.index

Index(['California', 'New York', 'Texas', 'Florida'], dtype='object')

#### Columns

In [24]:
# Columns - it is an index object holding the column labels
states.columns

Index(['population', 'area'], dtype='object')

### Dataframe as a specialized Dictionary

In [25]:
states["area"]

California    423967
New York      141297
Texas         695662
Florida       170312
Name: area, dtype: int64

# Constructing Dataframe Objects

### 1- From a Single Series objects

In [26]:
# A DataFrame is a collection of Series objects, and a single column DataFrame can be constructed from a single Series:
pd.DataFrame(population_series, columns=["population"])

            population
California       12345
New York         12346
Texas           147895
Florida         968574

### 2 - From a list of Dicts

In [27]:
# Any list of dictionaries can be made into a DataFrame. We’ll use a simple list comprehension to create some data:
data = [{'a': i, 'b':i*2} for i in range(5)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4
3  3  6
4  4  8

### 3 - From a 2-D Numpy array

In [28]:
c = pd.DataFrame(np.round(np.random.rand(3, 2), 2), columns=["foo", "bar"], index=[10, 20, 30])
c

     foo   bar
10  0.06  0.82
20  0.68  0.58
30  0.49  0.25