In [89]:
import numpy as np
import pandas as pd

# Data Selection in Series

### Series as a Dict

In [90]:
data = pd.Series([0.25, 0.5, 0.75, 1.0, 1.25, 1.5], index=['a', 'b', 'c', 'd', 'e', 'f'])
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
f    1.50
dtype: float64

In [91]:
data['d']

np.float64(1.0)

In [92]:
# We can also use dictionary-like Python expressions and methods to examine the keys/indices and values
print('b' in data)

True

In [93]:
# Just as you can extend a dictionary by assigning to a new key, you can extend a Series by assigning to a new index value
data['g'] = 1.75    # Adding g index in the data
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
f    1.50
g    1.75
dtype: float64

In [94]:
# Slicing by explicit index
data['a':'e']

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [95]:
# Slicing by implicit Integer index
data[1:5]

b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [96]:
# Masking
data[(data >= 1.25)]

e    1.25
f    1.50
g    1.75
dtype: float64

In [97]:
# Fancy Indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

#### Indexers: loc/iloc
These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.

In [98]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [99]:
# Explicit index when Indexing
data[1]

'a'

In [100]:
# Implicit index when Indexing
data[1:]

3    b
5    c
dtype: object

### Loc
Allows indexing and slicing that always references the explicit index

In [101]:
data.loc[1]

'a'

In [102]:
data.loc[1:3]

1    a
3    b
dtype: object

### iloc
Allows indexing and slicing that always references the implicit Python-style index

In [103]:
data.iloc[1]

'b'

In [104]:
data.iloc[1:3]

3    b
5    c
dtype: object

# Data Selection in DataFrame

### Dataframe as a dictionary

In [105]:
pop_dict = {'California':12345,
            'New York':12346,
            'Texas':147895,
            'Florida':968574}

area_dict = {'California': 423967,
            'New York': 141297,
            'Texas': 695662,
            'Florida': 170312}

population_series = pd.Series(pop_dict)
area_series = pd.Series(area_dict)

In [106]:
states = pd.DataFrame({"population": population_series,
                       "area": area_series})
states

            population    area
California       12345  423967
New York         12346  141297
Texas           147895  695662
Florida         968574  170312

In [107]:
# Accessing a single column
states["population"]

California     12345
New York       12346
Texas         147895
Florida       968574
Name: population, dtype: int64

In [108]:
# Add a new column
states["density"] = (states["population"] / states["area"]) * 100
states

            population    area     density
California       12345  423967    2.911783
New York         12346  141297    8.737624
Texas           147895  695662   21.259606
Florida         968574  170312  568.705670

### Dataframe as a 2-d array

In [109]:
states.values

array([[1.23450000e+04, 4.23967000e+05, 2.91178323e+00],
       [1.23460000e+04, 1.41297000e+05, 8.73762359e+00],
       [1.47895000e+05, 6.95662000e+05, 2.12596060e+01],
       [9.68574000e+05, 1.70312000e+05, 5.68705670e+02]])

In [110]:
# Transpose
states.T

               California       New York          Texas       Florida
population   12345.000000   12346.000000  147895.000000  968574.00000
area        423967.000000  141297.000000  695662.000000  170312.00000
density          2.911783       8.737624      21.259606     568.70567

In [111]:
states

            population    area     density
California       12345  423967    2.911783
New York         12346  141297    8.737624
Texas           147895  695662   21.259606
Florida         968574  170312  568.705670

In [112]:
# iloc
states.iloc[:3, :2]

            population    area
California       12345  423967
New York         12346  141297
Texas           147895  695662

In [113]:
# loc
states.loc[:"Texas", ["area", "density"]]

              area    density
California  423967   2.911783
New York    141297   8.737624
Texas       695662  21.259606

### Additional indexing conventions

While indexing refers to columns, slicing refers to rows

In [114]:
states

            population    area     density
California       12345  423967    2.911783
New York         12346  141297    8.737624
Texas           147895  695662   21.259606
Florida         968574  170312  568.705670

In [115]:
# Slicing
states["New York": "Texas"]

          population    area    density
New York       12346  141297   8.737624
Texas         147895  695662  21.259606

In [116]:
# Such slices can also refer to rows by number rather than by index:
states[1:3]

          population    area    density
New York       12346  141297   8.737624
Texas         147895  695662  21.259606

In [118]:
# Similarly, direct masking operations are also interpreted row-wise rather than column-wise
states[states.density > 20]

         population    area     density
Texas        147895  695662   21.259606
Florida      968574  170312  568.705670