In [81]:
import numpy as np
import pandas as pd

## None:Pythonic missing data

In [82]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [83]:
# The use of Python objects in an array also means that if you perform aggregations like sum() or min() across an array with a None value, you will generally get an error

# vals1.sum() --> Error

## NaN:Missing numerical data
NaN is specifically a floating-point value; there is no equivalent NaN value for integers, strings, or other types

In [84]:
vals2 = np.array([1, np.nan, 3, 4])
vals2

array([ 1., nan,  3.,  4.])

In [85]:
# Regardless of the operation, the result of arithmetic with NaN will be another NaN
print(1 + np.nan)
print(7 * np.nan)
print(vals2.sum())  # Aggregates over Nan will not result in any error, but they are not useful
print(vals2.min())

# This will ignore the missing values
print(np.nansum(vals2))
print(np.nanmin(vals2))

nan
nan
nan
nan
8.0
1.0

## NaN and None in Pandas
NaN and None both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate

In [86]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

# Operating on Null Values

In [87]:
# isnull() --> Generate a Boolean mask indicating missing values
# notnull() --> Opposite of isnull()
# dropna() --> Return a filtered version of the data
# fillna () --> Return a copy of the data with missing values filled or imputed

In [88]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [89]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

### Dropping null values

#### Dropna() on Series

In [90]:
data.dropna()

0        1
2    hello
dtype: object

#### Dropna() for dataframe
We cannot drop single values from a DataFrame; we can only drop full rows or full columns.

In [91]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5],
                  [np.nan, 4, 6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [92]:
# By default dropna() will remove any row which has missing values
df.dropna()

     0    1  2
1  2.0  3.0  5

In [93]:
# Alternatively, you can drop NA values along a different axis, axis=1 drops all columns containing a null value
df.dropna(axis=1)

   2
0  2
1  5
2  6

### Filling null values

#### Filling null values in Series

In [94]:
data = pd.Series([1, np.nan, 2, None, 3], index=['a', 'b', 'c', 'd', 'e'])
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [95]:
# We can fill NA entries with a single value, such as zero
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [96]:
# We can specify a forward-fill to propagate the previous value forward
data.ffill()    # forward-fill

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [97]:
# Or we can specify a back-fill to propagate the next values backward
data.bfill()    # backward-fill

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

#### Filling null values in Dataframe
We can also specify an axis along which the fills take place

In [98]:
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [101]:
df.ffill(axis=1)

     0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0