In [1]:
import numpy as np
import pandas as pd

# One-to-one Join
The pd.merge() function recognizes that each DataFrame has an “employee” column,
and automatically joins using this column as a key. The result of the merge is a new
DataFrame that combines the information from the two inputs. Notice that the order
of entries in each column is not necessarily maintained: in this case, the order of the
“employee” column differs between df1 and df2, and the pd.merge() function correctly
accounts for this. Additionally, keep in mind that the merge in general discards
the index, except in the special case of merges by index

In [2]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

In [6]:
print(df1)
print("\n")
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [13]:
# To combine this information into a single DataFrame, we can use the pd.merge() function
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

# Many-to-one Joins
Many-to-one joins are joins in which one of the two key columns contains duplicate
entries. For the many-to-one case, the resulting DataFrame will preserve those duplicate
entries as appropriate.

In [11]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']}
)

In [14]:
df4

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [15]:
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [16]:
pd.merge(df3, df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

# Many-to-many Joins
Many-to-many joins are a bit confusing conceptually, but are nevertheless well
defined. If the key column in both the left and right array contains duplicates, then
the result is a many-to-many merge. This will be perhaps most clear with a concrete
example. Consider the following, where we have a DataFrame showing one or more
skills associated with a particular group.

In [17]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organization']})

In [18]:
df5

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [19]:
pd.merge(df1, df5)

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

# Specification of the merge key

## The on keyword
This option works only if both the left and right DataFrames have the specified column
name.

In [24]:
df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [25]:
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [26]:
pd.merge(df1, df2, on="employee")

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

## The left_on and right_on keywords

In [27]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
df3

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [28]:
print(df1)
print(df3)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [30]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop("name", axis=1)

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

## The left_index and right_index keywords
Sometimes, rather than merging on a column, you would instead like to merge on an
index.

In [31]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

In [32]:
print(df1a)
print(df2a)

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [33]:
# You can use the index as the key for merging by specifying the left_index and/or right_index flags in pd.merge()
pd.merge(df1a, df2a, left_index=True, right_index=True)

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [34]:
# If you’d like to mix indices and columns, you can combine left_index with right_on or left_on with right_index to get the desired behavior
print(df1a)
print(df3)

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [35]:
pd.merge(df1a, df3, left_index=True, right_on="name")

         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

# Specifying Set arithmetic for Joins

In [37]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']})
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']})

In [39]:
print(df6)
print("\n")
print(df7)

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread


     name drink
0    Mary  wine
1  Joseph  beer

In [40]:
# Here we have merged two datasets that have only a single “name” entry in common: Mary. By default, the result contains the intersection of the two sets of inputs; this is what is known as an inner join. We can specify this explicitly using the "how" keyword, which defaults to 'inner'
pd.merge(df6, df7)

   name   food drink
0  Mary  bread  wine

The rest options are: outer, left, right

# Overlapping Column Names: The suffixes Keyword

In [41]:
# Finally, you may end up in a case where your two input DataFrames have conflicting column names. Consider this example:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})

In [42]:
print(df8)
print("\n")
print(df9)

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4


   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

In [45]:
# These suffixes work in any of the possible join patterns, and work also if there are multiple overlapping columns.
pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])

   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2